concurrency: ci-${{github.actor}}
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - developement
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: payment-form-test-0101    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    if: startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and run unit tests
      # add unit tests 
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: build
    environment:
       name: 'Development'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  test:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps: 
      # add e2e tests
    - name: Run e2e smoke tests
      run: echo Cypress tests passed 
      # # add performance tests
    - name: Run performance smoke tests 
      run: echo K6 tests passed

  auto-merge-dependabot:
    name: Auto merge dependabot PR
    needs: test
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      contents: write
    steps:
    - name: Merge PR from dependabot
      uses: fastify/github-action-merge-dependabot@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}
        target: any
        merge-method: rebase


