on:
  pull_request:
    branches:
      - developement
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: payment-form-test-0101    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  if: star
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and run unit tests
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      run: echo artifact uploaded successfully
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
       name: 'Development'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      run: echo artifact downloaded successfully
      uses: actions/download-artifact@v3
       with:
          name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      run: echo deploy to Azure WebApp completed gracefully
      # uses: azure/webapps-deploy@v2
      # with:
      #   app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #   publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #   package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  test:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps: 
    - name: Run e2e smoke tests
      run: echo Cypress tests passed 

    - name: Run performance smoke tests 
      run: echo K6 tests passed

  automerge:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Automatically merge Pull Request 
      run: echo Pull Request is merged
